spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netflix_clone
    username: root
    password: @@@@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ${JWT_SECRET:temporary-secret-key-please-change-this-in-production-min-32-bytes}
  expiration: 3600000