### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 콘텐츠 등록
POST http://localhost:8080/api/contents
Content-Type: application/json

{
  "title": "제목제목",
  "description": "제발 만들어졌으면",
  "genre": "SF",
  "director": "케이주"
}

### 전체 조회
GET http://localhost:8080/api/contents

### 단건 조회
GET http://localhost:8080/api/contents/1

### 수정
PUT http://localhost:8080/api/contents/1
Content-Type: application/json

{
  "title": "제목수정",
  "description": "수정했어요!!",
  "genre": "SF",
  "director": "케이주"
}

### 삭제
DELETE http://localhost:8080/api/contents/1

### 콘텐츠 등록
POST http://localhost:8080/api/contents
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzg5MzA5MDIzLCJleHAiOjE3ODkzMTI2MjN9.X3N4nv4YVuPZqyaRuhUlZA2fOfGMPm6QKDVnQyi2tpOZ2YgHKAhqhr7Hf-C4QEjcr9KLLMAUcWNwbwWSUCjrtg
Content-Type: application/json

{
  "title": "테스트",
  "description": "설명",
  "genre": "SF",
  "director": "감독"
}

### 장르 등록
POST http://localhost:8080/api/genres
Authorization: Bearer 토큰값
Content-Type: application/json

{
  "name": "SF",
  "name": "로맨스"
}

### 장르 전체 조회
GET http://localhost:8080/api/genres

### 콘텐츠 등록 (장르 포함)
POST http://localhost:8080/api/contents
Authorization: Bearer 관리자_토큰
Content-Type: application/json

{
  "title": "기묘한 이야기",
  "description": "1980년대 미국 배경 SF 스릴러",
  "director": "더퍼 형제",
  "genreIds": [1, 2]
}

### 조회해서 장르 이름이 잘 나오는지 확인
GET http://localhost:8080/api/contents/1