### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 콘텐츠 등록
POST http://localhost:8080/api/contents
Content-Type: application/json

{
  "title": "제목제목",
  "description": "제발 만들어졌으면",
  "genre": "SF",
  "director": "케이주"
}

### 전체 조회
GET http://localhost:8080/api/contents

### 단건 조회
GET http://localhost:8080/api/contents/1

### 수정
PUT http://localhost:8080/api/contents/1
Content-Type: application/json

{
  "title": "제목수정",
  "description": "수정했어요!!",
  "genre": "SF",
  "director": "케이주"
}

### 삭제
DELETE http://localhost:8080/api/contents/1